const ERROR_CODES = {
    CHECKER_LAMBDA_REJECTION: 1,
    FLOW_LAMBDA_REJECTION: 2,
    REQUEST_PARAMETER_MISSING: 3,
    CONFIGURATION_PARAMETER_MISSING: 4,
    INVALID_PARAMETER: 5,
    S3_READ_ERROR: 6,
    S3_WRITE_ERROR: 7,
    DYNAMO_DB_ERROR: 8,
    UNKNOWN_ERROR: 9,
    NOT_FOUND: 10,
    LOCALIZATION_ERROR: 11,
    CONFIGURATION_ERROR: 12,
    INSTANT_WIN_ALGORITHM_FUNCTION_ERROR: 13,
    INVALID_JSON_REQUEST: 14,
    IRREVERSIBLE_PARTICIPATION: 15,
    S3_DELETE_ERROR: 16,
    S3_LIST_OBJECTS_ERROR: 17,
    S3_GET_LIFECYCLE_ERROR: 18,
    S3_SET_LIFECYCLE_ERROR: 19,
    ECC_GET_REPGROUP_ERROR: 20,
    INVALID_VOUCHER_STATUS: 21,
    INVALID_CURRENCY_ID: 21,
};

const DYNAMO_DB_ERR_CODES = {
    DYNAMO_DB_ERROR_PUT: 10005,
    DYNAMO_DB_ERROR_UPDATE: 10006,
    DYNAMO_DB_ERROR_BATCH_WRITE: 10007,
    DYNAMO_DB_ERROR_TRANSACT_WRITE: 10008,
    DYNAMO_DB_ERROR_GET: 10009,
    DYNAMO_DB_ERROR_QUERY: 10010,
    DYNAMO_DB_ERROR_SCAN: 10011,
    DYNAMO_DB_ERROR_BATCH_GET: 10012,
    DYNAMO_DB_ERROR_TRANSACT_READ: 10013,
    DYNAMO_DB_ERROR_DELETE: 10014,
    MISSING_DYNAMO_DB_MANDATORY_PARAMS: 10015,
};

const GENERAL_ERR_CODES = {
    UNKNOWN_REASON: 10000,
    PARTICIPANT_IS_BLOCKED: 10002,
    MISSING_REQUEST_PARAMETERS: 10004,
    CONFIGURATION_MALFORMED: 10016,
    NONEXISTENT_FLOW_LABEL: 10017,
    INVALID_REQUEST_PARAMETERS: 10018,
    NONEXISTENT_CONFIGURATION: 10019,
    CONFIG_ACCESS_DENIED: 10031,
    REQUEST_RETRY: 10032,
    REFERRAL_CODE_ALREADY_USED: 10037,
    REFERRAL_LIMIT_REACHED: 10038,
    WALLET_IS_EMPTY: 10039,
};

const INSTANT_WIN_ERR_CODES = {
    NONEXISTENT_IW_ALGORITHM: 10001,
    IW_PRIZE_REDEEM_FAILED: 10003,
    CURRENCY_REDUCER_PARAMS_NOT_CONFIGURED: 10020,
    IW_PARTICIPATION_NOT_FOUND: 10021,
    IRREVERSIBLE_IW_PARTICIPATION: 10022,
    IW_DIGITAL_CODE_NOT_FOUND: 10023,
    IRREVERSIBLE_IW_VOUCHER: 10024,
    WINNING_MOMENT_NOT_FOUND: 10025,
};

const TRANSACTION_ERR_CODES = {
    CURRENCY_MARKET_DOES_NOT_MATCH_PROMO_MARKET: 10033,
    LOYALTY_TRANSACTION_FAILED: 10034,
    LOYALTY_REFEREE_REWARD_FAILED: 10035,
    LOYALTY_REFERRER_REWARD_FAILED: 10036,
};

module.exports = {
    ERROR_CODES,
    /**
     * New error codes. Generic errors should be avoided as much as possible, instead, we should create new value for every
     * distinguishable detail. Sometimes this is not possible and/or error handler is missing, which is why we still need
     * couple of generic errors as a 'default fallback' (Example: DynamoDB errors, REDEEM_PRIZE_ERROR for IW purposes)
     */
    ERR_CODES: {
        ...DYNAMO_DB_ERR_CODES,
        ...GENERAL_ERR_CODES,
        ...INSTANT_WIN_ERR_CODES,
        ...TRANSACTION_ERR_CODES,
    },
};
