const PLUGINS_MAP = {
    RS: 'ReceiptScanner',
};

const MIDDLEWARE_MAP = {
    CALL_EXTERNAL_SERVICE: 'callExternalService',
    UPDATE_PARTICIPATION: 'createOrAppendParticipation',
};

const PARAMS_REQUIRING_WRAPPERS = {
    RS_PROCESSING: 'signedUrls',
};

const PLUGINS_CONFIG_PARAMS = {
    FETCH_URL: 'fetchUrl',
    PARAMS: 'params',
    METHOD: 'method',
};

const REQUIRED_PARAMETERS_FOR_PLUGIN = {
    RS: [PLUGINS_CONFIG_PARAMS.FETCH_URL, PLUGINS_CONFIG_PARAMS.PARAMS, PLUGINS_CONFIG_PARAMS.METHOD],
};

const RS_TRANSACTION_STATUSES = {
    INVALID_RECEIPT: 'INVALID_RECEIPT',
    REVIEW: 'REVIEW',
    PROCESSED: 'PROCESSED',
    PROCESSING: 'PROCESSING',
    ERROR: 'ERROR',
};

module.exports = {
    PLUGINS_MAP,
    REQUIRED_PARAMETERS_FOR_PLUGIN,
    PARAMS_REQUIRING_WRAPPERS,
    MIDDLEWARE_MAP,
    RS_TRANSACTION_STATUSES,
};
